name: Cypress Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [profile-update, property-details, search, user-login]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          if [ "${{ matrix.group }}" == "profile-update" ]; then
            npx cypress run --spec "cypress/e2e/profileUpdate.cy.js"
          elif [ "${{ matrix.group }}" == "property-details" ]; then
            npx cypress run --spec "cypress/e2e/propertyDetails.cy.js"
          elif [ "${{ matrix.group }}" == "search" ]; then
            npx cypress run --spec "cypress/e2e/search.cy.js"
          elif [ "${{ matrix.group }}" == "user-login" ]; then
            npx cypress run --spec "cypress/e2e/userLogin.cy.js"
          fi

      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
