name: Playwright Tests CI

on:
  push:
    branches:
      - mariia-iakovenko
      - 'release/*'
      - 'feature/*'
  pull_request:
    branches:
      - mariia-iakovenko
      - 'release/*'
      - 'feature/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install

    - name: Load environment variables from test.env
      run: |
        cp env/test.env .env
        export $(grep -v '^#' .env | xargs)

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      env:
        TEST_ENV: test
      run: npx playwright test --reporter=html

    - name: Compress the report
      if: always()
      run: |
       zip -r playwright-report.zip playwright-report/

    - name: Upload Playwright Report to Artifactory
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report.zip

    - name: Upload ZIP to Uploadcare
      if: always()
      run: |
        curl -X POST \
          -F "UPLOADCARE_STORE=1" \
          -F "UPLOADCARE_PUB_KEY=$UPLOADCARE_PUB_KEY" \
          -F "file=@playwright-report.zip" \
          https://upload.uploadcare.com/base/

    - name: Cleanup
      run: rm -rf playwright-report.zip playwright-report/